import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Resume By Next JS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
		<html lang="en">
			<body className={inter.className}>
				<div className='min-h-screen'>
					<div className='grid grid-cols-12'>
						<section className='col-span-12 sm:col-span-4 md:col-span-2'>
							<Sidebar />
						</section>
						<main className='col-span-12 sm:col-span-8 md:col-span-10'>
							{children}
						</main>
					</div>
					<Footer/>
				</div>
			</body>
		</html>
    );
}
